export const ConstManager = {
    sellWindow: document.getElementById('sellSectionBox'),
    sellButton: document.getElementById('sellButton'),
    title: document.getElementById('titleInput'),
    location: document.getElementById('locationInput'),
    type: document.getElementById('typeInput'),
    rooms: document.getElementById('roomInput'),
    price: document.getElementById('priceInput'),
    surface: document.getElementById('surfaceInput'),
    description: document.getElementById('descInput'),
    mainImage: document.getElementById('mainImage'),
    burgerMenu: document.querySelector('.burgerMenu'),
    navLinks: document.querySelector('.navButtons'),
    roomBox: document.getElementById('roomId'),
    applyFilterButton: document.getElementById('applyFilterButton'),
    removeFilterButton: document.getElementById('removeFilterButton'),
    saveButton: document.getElementById('saveButton'),
    homeButton: document.getElementById('homeButton'),
    rentButton: document.getElementById('rentButton'),
    searchButton: document.getElementById('searchButton'),
}